/// <reference types="node" />
import { defineConfig } from "vitepress";
import { config as loadEnv } from "dotenv";
import { resolve } from "path";
import docsConfig from "./config.docs.mts";

/**
 * Package-managed VitePress configuration.
 *
 * DO NOT EDIT THIS FILE - your changes may be overwritten.
 * Instead, edit config.docs.mts for your customizations.
 */

// Load environment variables from Laravel's .env file
loadEnv({ path: resolve(__dirname, "../../../.env") });

// Base URL from VITEPRESS_BASE or VITEPRESS_ROUTE_PREFIX env variable
const routePrefix = process.env.VITEPRESS_ROUTE_PREFIX ?? "docs";
const base = process.env.VITEPRESS_BASE ?? `/${routePrefix}/`;

console.log(`[VitePress] Building with base URL: ${base}`);

export default defineConfig({
    // Merge user config
    ...docsConfig,

    // Package-managed settings (override user settings)
    base: base,

    // Package-managed head tags - these will be merged with user-defined head tags
    // The favicon is always added by the package; user tags are appended
    head: [
        ["link", { rel: "icon", href: `${base}favicon.ico` }],
        // Merge user-defined head tags
        ...(docsConfig.head ?? []),
    ],

    // Custom language aliases for markdown syntax highlighting (see https://shiki.style/languages)
    markdown: {
        languageAlias: {
            env: "dotenv",
        },
    },
});
